[package]
name = "tatar-baza"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["ws"] }
shuttle-axum = "0.52.0"
shuttle-runtime = "0.52.0"
tokio = { version = "1.43.0", features = ["full"] }
serde_json = "1.0"
futures = "0.3.31"

